version: "3.1"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker-data/postgres/data:/var/lib/postgresql/data
